server:
  ip: 192.168.1.45
  port: 8080

mybatis:
  #mapper-locations:
  #  - classpath:mapper/*.xml
  #  - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.chuweizi.customize.dto

spring:
  # yml配置的优先级高于java配置；如果yml配置和java配置同时存在，则yml配置会覆盖java配置
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      maxTotalConnect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      maxConnectPerRoute: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connectTimeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      readTimeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connectionRequestTimout: 200
      # 重试次数
      retryTimes: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keepAliveTime: 10
      # 针对不同的网址,长连接保持的存活时间,单位s,如果是频繁而持续的请求,可以设置小一点,不建议设置过大,避免大量无用连接占用内存资源
      keepAliveTargetHost:
        www.baidu.com: 5

zjg:
  # 智家狗服务域名
  serve: http://zjgdev.zstest.chuweizi.com
  # 智家狗key
  orgKey: -E8230CEB-DA9F-42A1-B9C9-228C8953CC77
  # 智家狗secret
  orgSecret: fb6109c1715bfe2d9e047d1b7120f2d9

hik:
  ip: 192.168.1.60
  port: 443
  appKey: 28903546
  appSecret: Arh7JoqFio5dd8Dbvjng